//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_sceneoperate : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.sceneoperate_Grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean Union
        {
            get
            {
                return SteamVR_Actions.sceneoperate_Union;
            }
        }
        
        public virtual SteamVR_Action_Boolean Delete
        {
            get
            {
                return SteamVR_Actions.sceneoperate_Delete;
            }
        }
        
        public virtual SteamVR_Action_Boolean Update
        {
            get
            {
                return SteamVR_Actions.sceneoperate_Update;
            }
        }
        
        public virtual SteamVR_Action_Boolean Editor
        {
            get
            {
                return SteamVR_Actions.sceneoperate_Editor;
            }
        }
        
        public virtual SteamVR_Action_Boolean SelectMenu
        {
            get
            {
                return SteamVR_Actions.sceneoperate_SelectMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean SaveMesh
        {
            get
            {
                return SteamVR_Actions.sceneoperate_SaveMesh;
            }
        }
        
        public virtual SteamVR_Action_Boolean Intersection
        {
            get
            {
                return SteamVR_Actions.sceneoperate_Intersection;
            }
        }
        
        public virtual SteamVR_Action_Boolean Subtract
        {
            get
            {
                return SteamVR_Actions.sceneoperate_Subtract;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.sceneoperate_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.sceneoperate_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchPos
        {
            get
            {
                return SteamVR_Actions.sceneoperate_TouchPos;
            }
        }
        
        public virtual SteamVR_Action_Boolean Touch
        {
            get
            {
                return SteamVR_Actions.sceneoperate_Touch;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.sceneoperate_Haptic;
            }
        }
    }
}
